spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: my_user
    password: ENC(58B2+Q05JnmNWOzdv1r40LI+ajnpa5MJiBJNcpHwTHYfnOiL+fObZfKzKwucYGOS)
    driver-class-name: oracle.jdbc.OracleDriver
  application:
    name: short-url
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect

# Jasypt
jasypt:
  encryptor:
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}
    password: "aaa"
    algorithm: "PBEWITHHMACSHA512ANDAES_256"
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    # jasypt-spring-boot 3.x 이상을 사용하는 경우 아래와 같이 pool-size를 1로 설정해야 할 수 있습니다.
    pool-size: 1

# Registration Key
registration:
  key: ENC(58B2+Q05JnmNWOzdv1r40LI+ajnpa5MJiBJNcpHwTHYfnOiL+fObZfKzKwucYGOS)

# JWT
jwt:
  secret: ENC(++CaXj5X9Uuo8y26uyogaB7t13TUnsiIagg8HCevTyPzhA6nW7SPSt4uJ5VS84MhOniyODqzlHW20urAnf/7Rtw8A9MaydLywp1QWV6awpn1SihcQBFifIKlJRvltCD+2yRwPfpYgQXetrVzeN5Mg8f1VBnknvITajJBJZgEzEI=)
  expiration: 3600000