# --- Local 환경 설정 ---
spring:
  # H2 인-메모리 데이터베이스 설정으로 변경
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=Oracle  # H2를 Oracle 호환 모드로 실행
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop # 로컬에서는 실행 시 스키마를 생성하고 종료 시 삭제
    show-sql: true # SQL 쿼리를 로그로 보여줌
    database-platform: org.hibernate.dialect.H2Dialect # H2 Dialect로 변경
  # H2 웹 콘솔 활성화
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# 로컬 환경용 JWT 비밀키 (환경변수 우선, Base64 기본값 제공)
jwt:
  # secret: ${LOCAL_JWT_SECRET:dAvU+ok0uxdNJADgmnhryNETOxcJCIK6ETe9khKhoPK9WT96GspP7VQ81n9QQJ3f2VLznWXa4VEDF3ejwUmUEA==}
  secret: ENC(0dy0bBuu5nd/sGwye3lYULFmELpgFxHWhd/FwENILoRkPyIqymvOYqm3V1roYPaXOwQzMuOnGcu1EZvfS5oF0MruRTyKF3kne1a+bGU7zUJDmorKdoXMlsMW3qE1BBTzcVL0t9hoxFHS5+OHq+8qfHuutRrmPTNp0vbldT+Fiyw=)

base-url: http://localhost:8080/

jasypt:
  encryptor:
    password: shortUrlApi # 로컬 개발용 마스터 키

logging:
  level:
    root: INFO
    '[org.springframework.security]': DEBUG
    '[com.nh.shorturl]': DEBUG

# short-url-redirect 모듈의 API 주소
short-url:
  redirect:
    api.base-url: http://localhost:8081