spring:
  # 1. 기본 활성화 프로파일 지정
  profiles:
    active: local
  # 2. 모든 환경에 공통적인 애플리케이션 이름
  application:
    name: short-url
  # 3. 모든 환경에 공통적인 JPA 네이밍 전략
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# 4. 모든 환경에 공통적인 Jasypt 설정
jasypt:
  encryptor:
    password: ${JASYPT_ENCRYPTOR_PASSWORD} # 환경변수에서 마스터 키를 가져옴
    algorithm: "PBEWITHHMACSHA512ANDAES_256"
    iv-generator-classname: org.jasypt.iv.RandomIvGenerator
    pool-size: 1

# 5. 모든 환경에 공통적인 JWT 만료 시간
jwt:
  expiration: 3600000 # 1시간


short-url:
  redirect:
    public-url: http://localhost:8081/